$target = ".\THIRD_PARTY_NOTICES.md"

$generated = (nuget-license -i .\CollapseLauncher.sln -o Markdown | Out-String).TrimEnd("`r", "`n")
$existing  = Get-Content $target -Raw

$day = (Get-Date).Day
$suffix = if ($day -in 11..13) {
  "th"
} elseif ($day % 10 -eq 1) {
  "st"
} elseif ($day % 10 -eq 2) {
  "nd"
} elseif ($day % 10 -eq 3) {
  "rd"
} else {
  "th"
}
$dateStamp = (Get-Date -Format "MMMM ") + "$day$suffix, " + (Get-Date -Format "yyyy")

$existing = $existing -replace `
  "This page lists the third-party software dependencies used in CollapseLauncher\..*",
  "This page lists the third-party software dependencies used in CollapseLauncher. Autogenerated by nuget-license at $dateStamp."


$pattern = "(?s)<!-- BEGIN NUGET-LICENSES -->.*?<!-- END NUGET-LICENSES -->"
$replacement = "<!-- BEGIN NUGET-LICENSES -->`n$generated`n<!-- END NUGET-LICENSES -->"

($existing -replace $pattern, $replacement) | Set-Content $target -NoNewline

$status = git diff -- $gitPath
if ([string]::IsNullOrWhiteSpace($status)) 
{
    git add $target 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "No license changes detected."
        return
    }

    git commit -m "[skip ci]chore: update third-party dependency licenses"

    #git push 2>$null
    if ($LASTEXITCODE -ne 0) {
        throw "git push failed"
    }
} else {
    Write-Host "No license changes detected."
}
   