//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -GenerateColorBindings -GenerateDependencyObject -Language CSharp -Namespace CollapseLauncher.AnimatedVisuals.Lottie -Public -WinUIVersion 3.0 -InputFile StartGameIcon.json
//       
//       Input file:
//           StartGameIcon.json (8234 bytes created 16:59+07:00 Jan 4 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    77 |
// |--------------------------+-------|
// | Expression animators     |    12 |
// | KeyFrame animators       |     6 |
// | Reference parameters     |    15 |
// | Expression operations    |    18 |
// |--------------------------+-------|
// | Animated brushes         |     3 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |    12 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     3 |
// | CompositionSpriteShapes  |     3 |
// |--------------------------+-------|
// | Brushes                  |     3 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Media;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace CollapseLauncher.AnimatedVisuals.Lottie
{
    // Name:        StartGameIcon
    // Frame rate:  60 fps
    // Frame count: 40
    // Duration:    666.7 mS
    public sealed partial class StartGameIcon
        : BindableThemeChangeAnimation
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        protected override void OnForegroundChanged(Brush brush)
        {
            if (brush is SolidColorBrush colorBrush)
            {
                Color_FFFFFF = colorBrush.Color;
                return;
            }

            if (brush is AcrylicBrush acrylicBrush)
            {
                Color_FFFFFF = acrylicBrush.TintColor;
                return;
            }
        }

        private static Color GetForegroundColor(bool isLightTheme) =>
            isLightTheme
                ? Color.FromArgb(0xFF, 0x00, 0x00, 0x00)
                : Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);

        // Animation duration: 0.667 seconds.
        internal const long c_durationTicks = 6666666;

        CompositionPropertySet _themeProperties;

        /// <summary>
        /// Dependency property for Color_FFFFFF.
        /// </summary>
        public static readonly DependencyProperty Color_FFFFFFProperty =
            DependencyProperty.Register("Color_FFFFFF", typeof(Color), typeof(StartGameIcon),
                new PropertyMetadata(GetForegroundColor(InnerLauncherConfig.IsAppThemeLight), OnColor_FFFFFFChanged));

        // Theme properties.
        public Color Color_FFFFFF
        {
            get => (Color)GetValue(Color_FFFFFFProperty);
            set => SetValue(Color_FFFFFFProperty, value);
        }

        static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        static void OnColor_FFFFFFChanged(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((StartGameIcon)d)._themeProperties?.InsertVector4("Color_FFFFFF", ColorAsVector4((Color)(Color)args.NewValue));
        }

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties == null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Color_FFFFFF", ColorAsVector4((Color)Color_FFFFFF));
            }
            return _themeProperties;
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            var res = 
                new StartGameIcon_AnimatedVisual(
                    compositor,
                    _themeProperties
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 40d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(6666666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 40d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
            if (propertyName == "Color_FFFFFF")
            {
                Color_FFFFFF = value;
            }
            else
            {
                return;
            }

            if (_themeProperties != null)
            {
                _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
            }
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class StartGameIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 6666666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            AnimationController _animationController_0;
            AnimationController _animationController_1;
            AnimationController _animationController_2;
            AnimationController _animationController_3;
            AnimationController _animationController_4;
            AnimationController _animationController_5;
            CompositionColorBrush _themeColor_Color_FFFFFF_0;
            CompositionColorBrush _themeColor_Color_FFFFFF_1;
            CompositionColorBrush _themeColor_Color_FFFFFF_2;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionRectangleGeometry _rectangle_1036;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            ScalarKeyFrameAnimation _positionXScalarAnimation_m11p5_to_124p125;
            StepEasingFunction _holdThenStepEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            void BindProperty2(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName0,
                CompositionObject referencedObject0,
                string referenceParameterName1,
                CompositionObject referencedObject1)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName0, referencedObject0);
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName1, referencedObject1);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress*0.4+0.6", "_", _root);
                return result;
            }

            AnimationController AnimationController_1()
            {
                if (_animationController_1 != null) { return _animationController_1; }
                var result = _animationController_1 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_1, "Progress", "_.Progress*0.3333333+0.6666667", "_", _root);
                return result;
            }

            AnimationController AnimationController_2()
            {
                if (_animationController_2 != null) { return _animationController_2; }
                var result = _animationController_2 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_2, "Progress", "_.Progress*0.5728853+0.2864427", "_", _root);
                return result;
            }

            AnimationController AnimationController_3()
            {
                if (_animationController_3 != null) { return _animationController_3; }
                var result = _animationController_3 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_3, "Progress", "_.Progress*0.3333333+0.3333333", "_", _root);
                return result;
            }

            AnimationController AnimationController_4()
            {
                if (_animationController_4 != null) { return _animationController_4; }
                var result = _animationController_4 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_4, "Progress", "_.Progress*0.4453252", "_", _root);
                return result;
            }

            AnimationController AnimationController_5()
            {
                if (_animationController_5 != null) { return _animationController_5; }
                var result = _animationController_5 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_5, "Progress", "_.Progress*0.3333333", "_", _root);
                return result;
            }

            // ShapeGroup: Rectangle 1 Offset:<30, 198>
            // Color bound to theme property value: Color_FFFFFF
            CompositionColorBrush ThemeColor_Color_FFFFFF_0()
            {
                if (_themeColor_Color_FFFFFF_0 != null) { return _themeColor_Color_FFFFFF_0; }
                var result = _themeColor_Color_FFFFFF_0 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 1F);
                BindProperty2(_themeColor_Color_FFFFFF_0, "Color", "ColorRGB(_theme.Color_FFFFFF.W*my.Opacity0,_theme.Color_FFFFFF.X,_theme.Color_FFFFFF.Y,_theme.Color_FFFFFF.Z)", "_theme", _themeProperties, "my", propertySet);
                return result;
            }

            // ShapeGroup: Rectangle 1 Offset:<30, 198>
            // Color bound to theme property value: Color_FFFFFF
            CompositionColorBrush ThemeColor_Color_FFFFFF_1()
            {
                if (_themeColor_Color_FFFFFF_1 != null) { return _themeColor_Color_FFFFFF_1; }
                var result = _themeColor_Color_FFFFFF_1 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 1F);
                BindProperty2(_themeColor_Color_FFFFFF_1, "Color", "ColorRGB(_theme.Color_FFFFFF.W*my.Opacity0,_theme.Color_FFFFFF.X,_theme.Color_FFFFFF.Y,_theme.Color_FFFFFF.Z)", "_theme", _themeProperties, "my", propertySet);
                return result;
            }

            // ShapeGroup: Rectangle 1 Offset:<30, 198>
            // Color bound to theme property value: Color_FFFFFF
            CompositionColorBrush ThemeColor_Color_FFFFFF_2()
            {
                if (_themeColor_Color_FFFFFF_2 != null) { return _themeColor_Color_FFFFFF_2; }
                var result = _themeColor_Color_FFFFFF_2 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                BindProperty2(_themeColor_Color_FFFFFF_2, "Color", "ColorRGB(_theme.Color_FFFFFF.W*my.Opacity0,_theme.Color_FFFFFF.X,_theme.Color_FFFFFF.Y,_theme.Color_FFFFFF.Z)", "_theme", _themeProperties, "my", propertySet);
                return result;
            }

            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(-11.5F, 128F));
                result.CenterPoint = new Vector2(30F, 198F);
                result.RotationAngleInDegrees = 45F;
                result.Scale = new Vector2(0.125F, 0.125F);
                // ShapeGroup: Rectangle 1 Offset:<30, 198>
                result.Shapes.Add(SpriteShape_0());
                BindProperty(_containerShape_0, "Offset", "Vector2(my.Position.X-30,my.Position.Y-198)", "my", _containerShape_0);
                return result;
            }

            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(-11.5F, 128F));
                result.CenterPoint = new Vector2(30F, 198F);
                result.RotationAngleInDegrees = 45F;
                result.Scale = new Vector2(0.125F, 0.125F);
                // ShapeGroup: Rectangle 1 Offset:<30, 198>
                result.Shapes.Add(SpriteShape_1());
                BindProperty(_containerShape_1, "Offset", "Vector2(my.Position.X-30,my.Position.Y-198)", "my", _containerShape_1);
                return result;
            }

            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(-11.5F, 128F));
                result.CenterPoint = new Vector2(30F, 198F);
                result.RotationAngleInDegrees = 45F;
                result.Scale = new Vector2(0.125F, 0.125F);
                // ShapeGroup: Rectangle 1 Offset:<30, 198>
                result.Shapes.Add(SpriteShape_2());
                BindProperty(_containerShape_2, "Offset", "Vector2(my.Position.X-30,my.Position.Y-198)", "my", _containerShape_2);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRectangleGeometry Rectangle_1036()
            {
                if (_rectangle_1036 != null) { return _rectangle_1036; }
                var result = _rectangle_1036 = _c.CreateRectangleGeometry();
                result.TrimEnd = 0.629999995F;
                result.TrimOffset = 0.75F;
                result.TrimStart = 0.370000005F;
                result.Offset = new Vector2(-518F, -518F);
                result.Size = new Vector2(1036F, 1036F);
                return result;
            }

            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<30, 198>
                var result = CreateSpriteShape(Rectangle_1036(), new Matrix3x2(1F, 0F, 0F, 1F, 30F, 198F));;
                result.StrokeBrush = ThemeColor_Color_FFFFFF_0();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 128F;
                return result;
            }

            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<30, 198>
                var result = CreateSpriteShape(Rectangle_1036(), new Matrix3x2(1F, 0F, 0F, 1F, 30F, 198F));;
                result.StrokeBrush = ThemeColor_Color_FFFFFF_1();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 128F;
                return result;
            }

            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<30, 198>
                var result = CreateSpriteShape(Rectangle_1036(), new Matrix3x2(1F, 0F, 0F, 1F, 30F, 198F));;
                result.StrokeBrush = ThemeColor_Color_FFFFFF_2();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 128F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.412999988F, 1F))
                    : _cubicBezierEasingFunction_1;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 8.91.
                result.InsertKeyFrame(0.222662598F, 1F, CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(1F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_1_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 1F, CubicBezierEasingFunction_0());
                // Frame 27.93.
                result.InsertKeyFrame(0.698220015F, 1F, CubicBezierEasingFunction_1());
                // Frame 40.
                result.InsertKeyFrame(0.99998045F, 0F, CubicBezierEasingFunction_0());
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_1_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 1F, CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(1F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // Position.X
            ScalarKeyFrameAnimation PositionXScalarAnimation_m11p5_to_124p125()
            {
                // Frame 0.
                if (_positionXScalarAnimation_m11p5_to_124p125 != null) { return _positionXScalarAnimation_m11p5_to_124p125; }
                var result = _positionXScalarAnimation_m11p5_to_124p125 = CreateScalarKeyFrameAnimation(0F, -11.5F, HoldThenStepEasingFunction());
                // Frame 40.
                result.InsertKeyFrame(1F, 124.125F, _c.CreateCubicBezierEasingFunction(new Vector2(0.47299999F, 0.523999989F), new Vector2(0.521000028F, 1F)));
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(256F, 256F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_0());
                shapes.Add(ContainerShape_1());
                shapes.Add(ContainerShape_2());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            internal StartGameIcon_AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(256F, 256F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _themeColor_Color_FFFFFF_0.Properties.StartAnimation("Opacity0", Opacity0ScalarAnimation_1_to_0(), AnimationController_0());
                _themeColor_Color_FFFFFF_1.Properties.StartAnimation("Opacity0", Opacity0ScalarAnimation_1_to_1(), AnimationController_2());
                _themeColor_Color_FFFFFF_2.Properties.StartAnimation("Opacity0", Opacity0ScalarAnimation_0_to_1(), AnimationController_4());
                _containerShape_0.Properties.StartAnimation("Position.X", PositionXScalarAnimation_m11p5_to_124p125(), AnimationController_1());
                _containerShape_1.Properties.StartAnimation("Position.X", PositionXScalarAnimation_m11p5_to_124p125(), AnimationController_3());
                _containerShape_2.Properties.StartAnimation("Position.X", PositionXScalarAnimation_m11p5_to_124p125(), AnimationController_5());
            }

            public void DestroyAnimations()
            {
                _themeColor_Color_FFFFFF_0.Properties.StopAnimation("Opacity0");
                _themeColor_Color_FFFFFF_1.Properties.StopAnimation("Opacity0");
                _themeColor_Color_FFFFFF_2.Properties.StopAnimation("Opacity0");
                _containerShape_0.Properties.StopAnimation("Position.X");
                _containerShape_1.Properties.StopAnimation("Position.X");
                _containerShape_2.Properties.StopAnimation("Position.X");
            }

        }
    }
}
